//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canifa_Clone
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int Id { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaMau { get; set; }
        public Nullable<int> MaSize { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual KichCo KichCo { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
