//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canifa_Clone
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int Id { get; set; }
        public string TenVoucher { get; set; }
        public string MaCode { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> DonToiThieu { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<bool> HienThi { get; set; }
    }
}
