//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canifa_Clone
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSanPham = new HashSet<AnhSanPham>();
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ChiTietSanPham = new HashSet<ChiTietSanPham>();
            this.DanhMuc1 = new HashSet<DanhMuc>();
        }
    
        public int MaSP { get; set; }
        public string SKU_Code { get; set; }
        public string TenSP { get; set; }
        public string Slug { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> PhanTramGiam { get; set; }
        public string MoTa { get; set; }
        public string ChatLieu { get; set; }
        public string HuongDanSD { get; set; }
        public Nullable<int> MaDM_Chinh { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsFreeship { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSanPham> ChiTietSanPham { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMuc1 { get; set; }
    }
}
